name: drupal-uni
recipe: drupal10
config:
  webroot: docroot
proxy:
  mailhog:
    - mail.drupal.uni.lando.site
  phpmyadmin:
    - phpmyadmin.drupal.uni.lando.site
services:
  mailhog:
    type: mailhog  
  phpmyadmin:
    type: phpmyadmin